import {
  Geist,
  Geist_Mono,
  Montserrat,
  Poppins,
  Pacifico,
  Bebas_Neue,
} from "next/font/google";
import "./globals.css";
import ClientLayout from "./ClientLayout.jsx";
import { SessionProvider } from "next-auth/react";
import ClientProvider from "./ClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["700", "900"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["700", "900"],
});

const pacifico = Pacifico({
  variable: "--font-pacifico",
  subsets: ["latin"],
  weight: "400",
});

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${poppins.variable} ${pacifico.variable} ${bebasNeue.variable} antialiased bg-linear-to-br from-blue-100 via-white to-blue-200 min-h-screen`}
      >
        <ClientProvider>
          <ClientLayout>{children}</ClientLayout>
        </ClientProvider>
      </body>
    </html>
  );
}
